// Central site configuration. Edit the TODO fields before going live.
export const SITE = {
  name: 'James Belanger',
  // Browser tab / default <title>
  title: 'James Belanger — Data, Language, AI Automation',
  // The three lanes, as printed on the hero's label strip.
  lanes: 'Data · Language · AI automation',
  tagline: 'I turn messy data into working tools.',
  // Default meta description.
  description:
    'James Belanger builds data pipelines, speech and language tools, and AI agent workflows, with the checks that make them trustworthy. Formerly a research technician in neurosurgery at Baylor College of Medicine.',
  bio: [
    'From 2024 to 2026 I was a research technician, and in practice the data person, in a neurosurgery lab at Baylor College of Medicine. We recorded single neurons in the brains of epilepsy patients while they listened and talked, and I built what turned those recordings into results: the sorting and quality-control pipeline the lab still runs, the speech transcription and alignment, and the statistical models. I also wrote the step-by-step guides, trained the staff who run those tools now, and was first-line technical support for recording sessions at two hospitals.',
    'Now I build the same kind of thing outside the lab. A pronunciation coach whose speech model runs entirely in your browser. A record matcher that shows which rule fired on every match. AI agent workflows that carry a ten-step procedure from start to finish, with a person approving the result before anything ships.',
  ],
  education: 'B.A. Cognitive Sciences, Rice University, 2025',
  // Human languages — the personal thread through all of it.
  languages: 'English, Spanish (professional) · French, Portuguese, Japanese (intermediate)',
  // Name pronunciation + transliterations shown under the tagline (NameScripts.astro). Each one has a spoken
  // clip at public/audio/name-<lang>.mp3, generated by scripts/make-name-audio.py — re-run it after edits here.
  // James's own pronunciation: buh-LAN-jer, stress on LAN, hard American r at the end (2026-10-05).
  // Transliterations follow it — James to verify each one.
  ipa: '/dʒeɪmz bəˈlændʒɚ/',
  nameScripts: [
    { lang: 'ja', label: 'Japanese', text: 'ジェームズ・ベランジャー' },
    { lang: 'ko', label: 'Korean', text: '제임스 벨란저' },
    { lang: 'hi', label: 'Hindi', text: 'जेम्स बेलैंजर' },
    { lang: 'ar', label: 'Arabic', text: 'جيمس بيلانجر', rtl: true },
    { lang: 'ru', label: 'Russian', text: 'Джеймс Беланджер' },
    { lang: 'el', label: 'Greek', text: 'Τζέιμς Μπελάντζερ' },
    { lang: 'he', label: 'Hebrew', text: 'ג׳יימס בלנג׳ר', rtl: true },
    { lang: 'zh', label: 'Chinese', text: '詹姆斯·贝兰杰' },
    { lang: 'th', label: 'Thai', text: 'เจมส์ เบแลนเจอร์' },
    { lang: 'am', label: 'Amharic', text: 'ጄምስ በላንጀር' },
    { lang: 'hy', label: 'Armenian', text: 'Ջեյմս Բելանջեր' },
  ] as { lang: string; label: string; text: string; rtl?: boolean }[],
  // Tagline split into constituents for the hover gloss (Gloss.astro).
  // cat = phrase category; es = Spanish gloss for that constituent.
  taglineGloss: [
    { text: 'I', cat: 'PRON', es: 'yo' },
    { text: 'turn', cat: 'V', es: 'convierto' },
    { text: 'messy data', cat: 'NP', es: 'datos desordenados' },
    { text: 'into working tools.', cat: 'PP', es: 'en herramientas que funcionan' },
  ],
  url: 'https://jamesbelanger.com',
  email: 'jamesluibelanger@gmail.com',
  location: 'Houston, TX',
  // og:image used for link previews (1200x630, generated by scripts/make-og.mjs).
  ogImage: '/og-image.png',
  links: {
    scholar: 'https://scholar.google.com/citations?user=8RCoKNUAAAAJ',
    orcid: 'https://orcid.org/0009-0003-3269-8810',
    github: 'https://github.com/JamesBelanger',
    linkedin: 'https://www.linkedin.com/in/jamesluibelanger',
  },
};

export const NAV = [
  { href: '/', label: 'About' },
  { href: '/projects', label: 'Projects' },
  { href: '/research', label: 'Research' },
  { href: '/publications', label: 'Publications' },
  { href: '/news', label: 'News' },
  { href: '/contact', label: 'Contact' },
];
